# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd222cd609feadd2ae6614b77a07c909c479b41e1349e961e8686a195bd937a1c85f8036e79c12faf0fdb1d950d153e77a69107fb65abaab4484847fabcba952

test:
  secret_key_base: f1d2cca3eff1600111b8afc36a5a30c33ecdba46121a56e50ce40cc77106984ca82fd0d910d228c022febd07bf0091cba574af2b45dae95df0b64ed0840169aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
